### ISSUE TITLE
Add binary release

### ISSUE THREAD

**Issue by amouat** [chainguard-dev/incert#8]
Releases should have downloadable binaries ideally created via an action.

**Comment by xnox** [comment]
copy and paste goreleaser.yaml action and config from anything else? i.e. https://github.com/chainguard-dev/terraform-provider-imagetest/actions/runs/9618304933/workflow ? but maybe using github artifact attestation?

**Comment by amouat** [comment]
Oh, that's a good idea...

**Comment by xnox** [comment]
gpg stuff likely is not needed here; as that's possibly just the terraform provider store requirement need.

**Comment by amouat** [comment]
We have a binary release now!

Huge thanks to @cpanato
